plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.0.145'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
    version = "8.8"
}

version = '0.2.6'
group = 'xyz.brassgoggledcoders.transport'
archivesBaseName = 'transport'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

jarJar.enable()

sourceSets {
    main {
        resources {
            srcDir 'src/generated/resources'
        }
    }
    datagen {
        compileClasspath += main.compileClasspath
        runtimeClasspath += main.runtimeClasspath
        compileClasspath += main.output
        runtimeClasspath += main.output
    }
    gametest {
        compileClasspath += main.compileClasspath
        runtimeClasspath += main.runtimeClasspath
        compileClasspath += main.output
        runtimeClasspath += main.output
    }
}

runs {
    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'

        modSource sourceSets.main
    }

    client {
        systemProperty 'forge.enabledGameTestNamespaces', 'transport'
        modSource sourceSets.gametest
    }

    server {
        systemProperty 'forge.enabledGameTestNamespaces', 'transport'
    }

    gameTestServer {
        systemProperty 'forge.enabledGameTestNamespaces', 'transport'
        modSource sourceSets.gametest
    }

    data {
        programArguments.addAll '--mod', 'transport', '--all', '--output', file('src/generated/resources/').getAbsolutePath(),
                '--existing', file('src/main/resources/').getAbsolutePath()
        modSource sourceSets.datagen
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

repositories {
    mavenLocal()
    maven {
        name = "Registrate"
        url = "https://maven.tterrag.com/"
    }
    maven {
        name = "BlameJared"
        url = "https://maven.blamejared.com/"
    }
    maven {
        name = "JEI"
        url = "https://dvs1.progwml6.com/files/maven"
    }
    maven {
        name "TOP"
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
}

dependencies {
    implementation "net.neoforged:neoforge:20.4.237"

    implementation "xyz.brassgoggledcoders.shadyskies:Registering:1.1.14"
    jarJar("xyz.brassgoggledcoders.shadyskies:Registering:[1.1.0, 1.2.0)")

    implementation "xyz.brassgoggledcoders.shadyskies:DataRegistering:1.1.6"

    localRuntime "blusunrize.immersiveengineering:ImmersiveEngineering:1.20.4-11.5.0-179"
    compileOnly "blusunrize.immersiveengineering:ImmersiveEngineering:1.20.4-11.5.0-179:api"

    compileOnly "mezz.jei:jei-1.20.4-neoforge-api:17.0.0.30"
    compileOnly "mezz.jei:jei-1.20.4-common-api:17.0.0.30"
    localRuntime "mezz.jei:jei-1.20.4-neoforge:17.0.0.30"

    implementation "curse.maven:the-one-probe-245211:5159289"
}

jar {
    archiveClassifier = "nodep"
    manifest {
        attributes([
                "Specification-Title"     : "Transport",
                "Specification-Vendor"    : "Brass Goggled Coders",
                "Specification-Version"   : "1",
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.jar.archiveVersion,
                "Implementation-Vendor"   : "Brass Goggled Coders",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

tasks.named("jarJar").configure {
    archiveClassifier = ""
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
    options.compilerArgs << "-Xmaxerrs" << "10000"
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}