modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Brass-Goggled-Coders/Transport/issues"

[[mods]]
    modId="transport"
    version="${file.jarVersion}"
    displayName="Transport"
    authors="SkySom"
    description='''
    '''

[[dependencies.transport]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.68,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.transport]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.16-30,)"
    side="BOTH"

[[dependencies.transport]]
    modId="titanium"
    mandatory=true
    versionRange="[1.16.1-3.0.0,)"
    side="BOTH"