modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Brass-Goggled-Coders/Transport/issues"
license="MIT"

[[mods]]
    modId="transport"
    version="${file.jarVersion}"
    displayName="Transport"
    authors="SkySom"
    description='''
    '''

[[dependencies.transport]]
    modId="neoforge"
    versionRange="[20.4,)"
    ordering="NONE"
    side="BOTH"