modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Brass-Goggled-Coders/Transport/issues"
license="MIT"

[[mods]]
    modId="transport"
    version="${file.jarVersion}"
    displayName="Transport"
    authors="SkySom"
    description='''
    '''

[[dependencies.transport]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.0,)"
    ordering="NONE"
    side="BOTH"