modLoader="javafml"
loaderVersion="[${loader_version},)"
issueTrackerURL="https://github.com/Brass-Goggled-Coders/Transport/issues"

[[mods]]
    modId="transport_ie"
    version="${version}"
    displayName="Transport:Immersive Engineering"
    authors="SkySom"
    description='''
    '''