modLoader="javafml"
loaderVersion="[${loader_version},)"
issueTrackerURL="https://github.com/Brass-Goggled-Coders/Transport/issues"

[[mods]]
    modId="transport_quark"
    version="${version}"
    displayName="Transport:Quark"
    authors="SkySom"
    description='''
    '''